# CONVERSION_FOUND - system has lib conversion
# CONVERSION_INCLUDE_DIR - conversion include directory
# CONVERSION_LIBRARIES - library needed to use conversion

if (CONVERSION_INCLUDE_DIR AND CONVERSION_LIBRARIES)
   set(CONVERSION_FIND_QUIETLY TRUE)
endif (CONVERSION_INCLUDE_DIR AND CONVERSION_LIBRARIES)

find_path(CONVERSION_INCLUDE_DIR NAMES converter.h PATH_SUFFIXES conversion)
find_library(CONVERSION_LIBRARIES NAMES conversion)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CONVERSION DEFAULT_MSG CONVERSION_INCLUDE_DIR CONVERSION_LIBRARIES)