FIND_PATH(RTM_INCLUDE_DIR rtm/rtm.h)

SET(RTM_NAMES ${RTM_NAMES} rtm)
FIND_LIBRARY(RTM_LIBRARY NAMES ${RTM_NAMES})

# handle the QUIETLY and REQUIRED arguments and set RTM_FOUND to TRUE if 
# all listed variables are TRUE

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RTM DEFAULT_MSG RTM_LIBRARY RTM_INCLUDE_DIR)

MARK_AS_ADVANCED(RTM_INCLUDE_DIR RTM_LIBRARY )
